### PR TITLE
Fix: slack message

### PR DESCRIPTION
**Pull request by ctlong**
When jobs in the cf-deployment `update-releases` pipeline fail they send slack alerts to the relevant team channels to let maintainers know their releases are failing to be pulled in.

The current message indicates that maintainers should reach out in the release-integration channel, which is no longer actively watched. They should instead reach out in the wg-app-runtime-deployments channel.

### CODE REVIEW

**Review by davewalter — COMMENTED** [review]
Do we want folks to reach out in #cf-deployment or #wg-app-runtime-deployments?

**Comment by ctlong** [comment]
> Do we want folks to reach out in #cf-deployment or #wg-app-runtime-deployments?

I went back and forth on this one.. I ended up choosing #cf-deployment because all the slack mappings right now are to product channels rather than working group channels.

If you have strong feelings about this then I can switch it to #wg-app-runtime-deployments?

**Comment by davewalter** [comment]
I think my thought process was that the notification was most useful to the working group, as we will be the ones to look at it and retrigger it.

**Comment by ctlong** [comment]
@davewalter updated it!

**Pull request merged**
