### PR TITLE
Add support for running routing smoke tests

### PR DESCRIPTION
**Pull request by shashwathi**
Hi Release Integration team,

Routing team would like to use runtime-ci scripts for running routing smoke tests. 

Signed-off-by: Edwin Xie <exie@pivotal.io>

### CODE REVIEW

**Comment by dsabeti** [comment]
Hey @shashwathi. Two things:
1. What's the priority of this change to you? Is it blocking work for the routing team, or are you just being helpful and contributing something upstream for the benefit of other users?
2. The task looks a lot like [our task to run CATs](https://github.com/cloudfoundry/cats-concourse-task/blob/master/task). I'm wondering if it makes more sense to try to make that task generic enough to handle both test suites.

**Comment by shashwathi** [comment]
@dsabeti 

> What's the priority of this change to you?

We would like to run all errands supported by routing release as a part of our pipeline. 

>Is it blocking work for the routing team?

We have a workaround to create our concourse task to run smoke tests but we do not want to maintain this task separately from routing acceptance tests. It makes sense to have them all under one repo.

> Are you just being helpful and contributing something upstream for the benefit of other users?

This could be a errand which upstream teams can run to test the functionality of TCP routing.
 
> The task looks a lot like our task to run CATs. I'm wondering if it makes more sense to try to 
make that task generic enough to handle both test suites.

I agree. If there is a generic task for both routing acceptance tests and routing smoke tests, it would be extremely helpful. 

Regards
Shash

**Comment by dsabeti** [comment]
@shashwathi. As I was digging around, I noticed that the smoke_tests are actually part of the acceptance tests. Does it make sense to run them at the same time as the acceptance tests in your pipeline? I'm pretty sure if we added `smoke_tests` to [this array](https://github.com/cloudfoundry/runtime-ci/blob/master/scripts/ci/run-rats/task#L15), we'd run the smoke tests as well.

**Comment by aaronshurley** [comment]
@dsabeti : 

> Does it make sense to run them at the same time as the acceptance tests in your pipeline? 
Yeah that could work.

Do you want us to create another PR for this? 

Regards
Aaron & @shashwathi

**Comment by dsabeti** [comment]
@aaronshurley Yeah, that would be great.

**Comment by shashwathi** [comment]
@dsabeti : 

Updated PR to run smoke tests as routing errands.

I have a question related to this PR. Other than routing team are there any teams consuming this task ? 
More context on why I am asking this question; we wrote our own task to run errands and not using this(rel-int) task any longer but our CI repo is still private. So if this task is present just to support our team then you can go ahead and delete the task.

Regards
Shash

**Comment by dsabeti** [comment]
@shashwathi. We run RATs in our pipeline, so we need that task for ourselves. I'd be surprised if any other team runs them, though.

**Pull request merged**
